"""reporter/markdown_reporter.py — GitHub-flavoured Markdown for web vuln scans."""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any


_SEV_EMOJI = {
    "CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡",
    "LOW": "🟢", "INFORMATIONAL": "🔵",
}


class MarkdownReporter:
    def render(self, data: dict[str, Any]) -> str:
        target   = data.get("target", data.get("url", "Unknown"))
        findings = data.get("findings", [])
        ts       = data.get("generated_at", datetime.utcnow().isoformat())

        counts: dict[str, int] = {}
        for f in findings:
            sev = f.get("severity", "LOW")
            counts[sev] = counts.get(sev, 0) + 1

        lines = [
            "# Web Vulnerability Scan Report",
            "",
            f"**Target:** `{target}`  ",
            f"**Generated:** {ts}  ",
            f"**Total Findings:** {len(findings)}",
            "",
            "## Summary",
            "",
            "| Severity | Count |",
            "|----------|-------|",
        ]
        for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"):
            c = counts.get(sev, 0)
            emoji = _SEV_EMOJI.get(sev, "")
            lines.append(f"| {emoji} **{sev}** | {c} |")

        lines += ["", f"## Findings ({len(findings)})", ""]

        for i, f in enumerate(findings, 1):
            sev   = f.get("severity", "LOW")
            emoji = _SEV_EMOJI.get(sev, "")

            lines.append(f"### [{i:03d}] {emoji} {f.get('title', '')}")
            lines.append("")
            lines.append("| Field | Value |")
            lines.append("|-------|-------|")
            lines.append(f"| **Severity** | `{sev}` |")
            lines.append(f"| **URL** | `{f.get('url', '')}` |")
            lines.append(f"| **OWASP** | {f.get('owasp_id', 'N/A')} |")
            lines.append("")
            lines.append(f"**Description:** {f.get('description', '')}")
            lines.append("")
            if f.get("evidence"):
                lines.append("**Evidence:**")
                lines.append("```")
                lines.append(f.get("evidence", ""))
                lines.append("```")
                lines.append("")
            lines.append(f"**Recommendation:** {f.get('recommendation', '')}")
            lines.append("")

            if f.get("mitre"):
                m = f["mitre"]
                lines.append(
                    f"**MITRE ATT&CK:** [{m.get('technique_id','')} — "
                    f"{m.get('technique_name','')}]({m.get('url','#')}) "
                    f"({m.get('tactic','')})"
                )
                lines.append("")

            lines.append("---")
            lines.append("")

        lines += [
            "> Generated by Web Vulnerability Scanner v2.0.0 · Authorized testing only",
        ]
        return "\n".join(lines)

    def save(self, data: dict[str, Any], path: str | Path) -> Path:
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(self.render(data), encoding="utf-8")
        return out
